services:
  - type: web
    name: sis315-dynamics365
    env: node
    plan: free
    buildCommand: "rm -rf backend/node_modules frontend/node_modules && cd backend && npm install --build-from-source && cd ../frontend && npm install --include=dev && node ./node_modules/vite/bin/vite.js build"
    startCommand: "cd backend && node server.js"
    envVars:
      - key: NODE_ENV
        value: production
