@echo off
echo Starting SIS315-Prototipo Microsoft Dynamics 365...
echo.
echo Starting backend server...
start cmd /k "cd backend && npm run dev"
timeout /t 3 >nul
echo Starting frontend server...
start cmd /k "cd frontend && npm run dev"
echo.
echo Both servers are starting...
echo Backend will be available at: http://localhost:5000
echo Frontend will be available at: http://localhost:5173
echo.
echo Press any key to close this window...
pause >nul
